version: "0.0.1"
services:
  php:
    image: "qq1060656096/php:7.2.2-kafka"
    volumes:
      - "./php/lib/php.ini:/usr/local/php/lib/php.ini:rw"
      - "./php/etc:/usr/local/php/etc:rw"
      - "./php/var/log:/usr/local/php/var/log:rw"
      - "./www:/data/webroot/www:rw"
    ports:
      - "19000:9000"
  nginx:
    image: "qq1060656096/nginx:1.13.4"
    volumes:
      - "./nginx/conf:/usr/local/nginx/conf:rw"
      - "./nginx/logs:/usr/local/nginx/logs:rw"
      - "./www:/data/webroot/www:rw"
    ports:
      - "1080:80"
  zookeeper:
    image: "wurstmeister/zookeeper:latest"
    ports:
      - "1281:2181"
  kafka:
    image: "wurstmeister/kafka:latest"
    ports:
      - "1902:9002"
  redis:
    image: "redis:latest"
    ports:
      - "16379:6379"